/*
 * Tabilet Explorer's SQL11 client.
 *
 * API adapter contract (implemented by SQL10): JSON responses from health,
 * overview, timeline, runs/{id}, todo, search, document, refresh, and
 * follow-up. All references are project-scoped by the server. The client
 * treats response text as untrusted and renders it with textContent.
 */
(function () {
  "use strict";
  const state = { view: "overview", timelineCursor: null, timelineNext: null, timelinePrevious: null, timelineFilters: {}, poll: null, generation: null };
  const $ = (id) => document.getElementById(id);
  const esc = (value) => String(value == null ? "" : value);
  const list = (value) => Array.isArray(value) ? value : [];
  const obj = (value) => value && typeof value === "object" ? value : {};
  function text(value) { return document.createTextNode(esc(value)); }
  function el(tag, attrs, children) {
    const node = document.createElement(tag);
    Object.entries(attrs || {}).forEach(([key, value]) => {
      if (key === "class") node.className = value;
      else if (key === "text") node.appendChild(text(value));
      else if (key === "html") node.textContent = value;
      else if (value !== false && value != null) node.setAttribute(key, value === true ? "" : value);
    });
    list(children).forEach((child) => node.append(child instanceof Node ? child : text(child)));
    return node;
  }
  function button(label, handler, attrs) { const b = el("button", Object.assign({ type: "button" }, attrs), [label]); b.addEventListener("click", handler); return b; }
  function source(ref) { const value = obj(ref); return el("span", { class: "source" }, [`${value.path || value.source_path || "source unavailable"}${value.line ? `:${value.line}` : ""}`]); }
  function badge(value, extra) { return el("span", { class: `badge ${extra || ""}` }, [value || "unknown"]); }
  function clear(node) { while (node.firstChild) node.removeChild(node.firstChild); }
  function showNotice(message) { $("notice").hidden = !message; $("notice").textContent = message || ""; }
  function showDiagnostics(items) {
    const values = list(items).map(esc).filter(Boolean); const node = $("diagnostics"); clear(node); node.hidden = values.length === 0;
    if (values.length) node.append(el("strong", {}, ["Diagnostics: "]), text(values.join("; ")));
  }
  async function api(path, options) {
    const response = await fetch(path, Object.assign({ headers: { Accept: "application/json" } }, options || {}));
    let body = {}; try { body = await response.json(); } catch (_) { body = { error: "The server returned an invalid response." }; }
    if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`);
    showDiagnostics(body.diagnostics || (body.index && body.index.diagnostics)); return body;
  }
  function setView(view, replace) {
    state.view = ["overview", "timeline", "todo"].includes(view) ? view : "overview";
    document.querySelectorAll("[data-view-panel]").forEach((panel) => { panel.hidden = panel.dataset.viewPanel !== state.view; });
    document.querySelectorAll("[data-view]").forEach((link) => { if (link.dataset.view === state.view) link.setAttribute("aria-current", "page"); else link.removeAttribute("aria-current"); });
    const url = new URL(location.href); url.searchParams.set("view", state.view); if (replace) history.replaceState({}, "", url); else history.pushState({}, "", url);
    if (state.view === "overview") loadOverview(); if (state.view === "timeline") loadTimeline(); if (state.view === "todo") loadTodo();
  }
  function renderCount(value) { return typeof value === "number" ? value : 0; }
  function renderOverview(data) {
    const body = obj(data); $("overview-freshness").textContent = body.index && body.index.refreshed_at ? `Indexed ${body.index.refreshed_at}` : "Index status unavailable";
    const root = $("overview-content"); clear(root);
    if (body.summary) root.append(el("p", { class: "card" }, [body.summary]));
    if (body.attention) { root.append(el("h3", {}, ["Needs attention"])); const attention = el("ul", { class: "attention-list" }); list(body.attention).forEach((item) => attention.append(el("li", { class: "attention-item" }, [el("strong", { text: item.title || item.kind || "Attention" }), el("p", { text: item.reason || "" }), item.source ? source(item.source) : ""]))); root.append(attention); }
    const sections = [["Active milestones and tasks", body.active_milestones || body.milestones, "milestone"], ["History", body.history, "history"], ["Archives", body.archives, "archive"], ["Evolution", body.evolution, "evolution"]];
    sections.forEach(([title, records, kind]) => { const items = list(records); const wrap = el("section", { class: "overview-section" }, [el("h3", {}, [title])]); if (!items.length) wrap.append(el("p", { class: "muted" }, ["No indexed records available."])); else { const grid = el("div", { class: "card-grid" }); items.forEach((item) => { const card = el("article", { class: "card" }); card.append(el("h3", { text: item.title || item.name || item.milestone_id || item.path || "Untitled" })); if (item.summary || item.description) card.append(el("p", { text: item.summary || item.description })); if (kind === "milestone") { const counts = obj(item.counts || item.states); const stats = el("div", { class: "stats" }); ["pending", "in_progress", "blocked", "completed", "cancelled", "historical"].forEach((key) => { if (counts[key] != null) stats.append(badge(`${key.replace("_", " ")}: ${counts[key]}`, `state-${key}`)); }); card.append(stats); } if (item.outcome) card.append(badge(item.outcome, `outcome-${item.outcome}`)); if (item.source) card.append(source(item.source)); grid.append(card); }); wrap.append(grid); } root.append(wrap); });
    if (!root.firstChild) root.append(el("p", { class: "muted" }, ["No overview evidence is available yet."]));
  }
  async function loadOverview() { try { renderOverview(await api("/api/overview")); } catch (error) { const root = $("overview-content"); clear(root); root.append(el("p", { class: "diagnostic", text: error.message })); } }
  function timelineEntry(item) {
    const entry = el("li", { class: "timeline-entry" }); const when = item.started_at || item.recorded_at || item.occurred_at; const time = el("time", { datetime: when || "" }, [when || "Time unavailable"]); entry.append(time);
    const content = el("div"); content.append(el("h3", {}, [item.operation || "Recorded operation"])); content.append(el("p", { text: item.summary || item.request_summary || item.result || "No summary recorded." })); if (item.capture_fidelity || item.fidelity) content.append(el("span", { class: "capture" }, [`Capture: ${item.capture_fidelity || item.fidelity}`])); if (item.milestone_id) content.append(el("span", { class: "source" }, [`Milestone ${item.milestone_id}`])); entry.append(content);
    entry.append(button("Open", () => openRun(item.run_id), { "aria-label": `Open ${item.operation || "run"} details` })); return entry;
  }
  async function loadTimeline(cursor) { const query = new URLSearchParams(); Object.entries(state.timelineFilters).forEach(([key, value]) => { if (value) query.set(key, value); }); const search = new URL(location.href).searchParams.get("search"); if (search) query.set("search", search); if (cursor) query.set("cursor", cursor); try { const data = await api(`/api/timeline?${query}`); const body = obj(data); state.timelineNext = body.next_cursor || body.next || null; state.timelinePrevious = body.previous_cursor || body.previous || null; const root = $("timeline-content"); clear(root); const entries = list(body.entries || body.runs || body.results); if (!entries.length) root.append(el("p", { class: "muted" }, ["No recorded workflow entries match these filters."])); else { const ul = el("ol", { class: "timeline-list" }); entries.forEach((item) => ul.append(timelineEntry(item))); root.append(ul); } renderTimelinePagination(); } catch (error) { const root = $("timeline-content"); clear(root); root.append(el("p", { class: "diagnostic", text: error.message })); } }
  function renderTimelinePagination() { const root = $("timeline-pagination"); clear(root); if (state.timelinePrevious) root.append(button("Previous", () => loadTimeline(state.timelinePrevious))); if (state.timelineNext) root.append(button("Next", () => loadTimeline(state.timelineNext))); }
  function todoItem(item, group) { const row = el("li", { class: "todo-item" }); const main = el("div", { class: "task-main" }); main.append(el("h4", { text: item.label || item.task_label || "Unnamed task" })); main.append(el("p", { class: "meta", text: item.reason || item.notes || "" })); if (item.milestone_id) main.append(el("span", { class: "source", text: `Milestone ${item.milestone_id} ` })); if (item.source) main.append(source(item.source)); if (item.prerequisites && item.prerequisites.length) main.append(el("p", { class: "meta", text: `Prerequisites: ${item.prerequisites.join(", ")}` })); row.append(main); const actions = el("div", { class: "task-actions" }); const action = group === "blocked" ? "investigate" : group === "needs_review" ? "review" : group === "waiting" ? "clarify" : "continue"; actions.append(button(group === "blocked" ? "Investigate" : group === "needs_review" ? "Review" : group === "waiting" ? "Clarify" : "Continue", () => prepareFollowUp(action, item), { "aria-label": `${action} ${item.label || "task"}` })); row.append(actions); return row; }
  function renderTodo(data) { const body = obj(data); const valid = body.validated !== false && body.recommendations_available !== false; $("todo-validation").textContent = valid ? "Validated" : "Recommendations withheld"; const root = $("todo-content"); clear(root); if (body.validation_reason) root.append(el("p", { class: "diagnostic", text: body.validation_reason })); const groups = [["Resume", "resume"], ["Ready", "ready"], ["Waiting", "waiting"], ["Blocked", "blocked"], ["Needs review", "needs_review"]]; groups.forEach(([title, key]) => { const records = list(body[key]); const section = el("section", { class: "todo-group" }, [el("h3", {}, [title, badge(String(records.length))])]); if (!records.length) section.append(el("p", { class: "muted" }, ["None"])); else { const ul = el("ul", { class: "todo-list" }); records.forEach((item) => ul.append(todoItem(item, key))); section.append(ul); } root.append(section); }); }
  async function loadTodo() { try { renderTodo(await api("/api/todo")); } catch (error) { const root = $("todo-content"); clear(root); root.append(el("p", { class: "diagnostic", text: error.message })); } }
  function detailSection(title, children) { return el("section", { class: "detail-section" }, [el("h3", {}, [title]), ...children]); }
  function openPanel(title, content) { $("detail-title").textContent = title; const root = $("detail-content"); clear(root); root.append(content); $("detail-panel").hidden = false; $("backdrop").hidden = false; $("close-detail").focus(); }
  async function openRun(runId) { if (!runId) return; const url = new URL(location.href); url.searchParams.set("run", runId); history.pushState({}, "", url); try { const body = await api(`/api/runs/${encodeURIComponent(runId)}`); const run = obj(body.run || body); const root = el("div"); root.append(detailSection("Recorded then", [el("p", { text: run.request_text || run.request_summary || "Request text was not captured." }), badge(run.capture_fidelity || run.fidelity || "incomplete") ])); root.append(detailSection("Outputs and phases", [el("pre", { text: run.output || run.summary || "No selected output was recorded." })])); const events = list(run.events || body.events); if (events.length) root.append(detailSection("Observed activity", events.map((event) => el("p", {}, [el("strong", { text: event.event_type || "event" }), " — ", event.summary || event.details || "", event.source ? source(event.source) : ""])))); root.append(detailSection("Current state", [el("p", { class: "muted", text: run.current_state || "Current source state must be checked separately." })])); openPanel(run.operation || "Run details", root); } catch (error) { openPanel("Run details unavailable", el("p", { class: "diagnostic", text: error.message })); } }
  async function prepareFollowUp(action, item) { try { showNotice("Validating the current source state…"); const body = await api("/api/follow-up", { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify({ action, milestone_id: item.milestone_id, task_id: item.explicit_id, task_label: item.label || item.task_label, source: item.source }) }); showNotice(""); const root = el("div"); root.append(el("p", { class: "muted", text: body.validation_note || "Prepared from validated current source state. Copying does not execute work." })); const prompt = el("pre", { class: "prompt", tabindex: "0" }, [body.prompt || "No prompt was prepared."]); root.append(prompt); root.append(el("div", { class: "prompt-actions" }, [button("Copy prompt", async () => { try { await navigator.clipboard.writeText(body.prompt || ""); showNotice("Prompt copied."); } catch (_) { prompt.focus(); showNotice("Clipboard access is unavailable. Select the prompt text and copy it manually."); } }), button("Select prompt", () => { const range = document.createRange(); range.selectNodeContents(prompt); const selection = window.getSelection(); selection.removeAllRanges(); selection.addRange(range); prompt.focus(); })])); openPanel(`${action.replace("_", " ")} follow-up`, root); } catch (error) { showNotice(""); openPanel("Follow-up unavailable", el("p", { class: "diagnostic", text: error.message })); } }
  async function refresh() { try { showNotice("Refreshing the derived index…"); const body = await api("/api/refresh", { method: "POST", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: "{}" }); showNotice(body.message || "Project refreshed."); await loadCurrent(); } catch (error) { showNotice(`Refresh failed: ${error.message}`); } }
  async function loadCurrent() { try { const body = await api("/api/health"); const project = obj(body.project || body); state.generation = body.index && body.index.generation || body.generation || state.generation; $("project-name").textContent = project.name || project.project_name || "Tabilet project"; $("project-context").textContent = [project.branch, project.git_head, body.index && body.index.refreshed_at ? `Indexed ${body.index.refreshed_at}` : "Index not refreshed"].filter(Boolean).join(" · "); } catch (error) { $("project-name").textContent = "Tabilet Explorer"; showDiagnostics([error.message]); } if (state.view === "overview") await loadOverview(); else if (state.view === "timeline") await loadTimeline(); else await loadTodo(); }
  function closePanel() { $("detail-panel").hidden = true; $("backdrop").hidden = true; const url = new URL(location.href); url.searchParams.delete("run"); history.pushState({}, "", url); }
  function setup() { const params = new URLSearchParams(location.search); setView(params.get("view") || "overview", true); document.querySelectorAll("[data-view]").forEach((link) => link.addEventListener("click", (event) => { event.preventDefault(); setView(link.dataset.view, false); })); window.addEventListener("popstate", () => { const current = new URL(location.href); setView(current.searchParams.get("view") || "overview", true); if (current.searchParams.get("run")) openRun(current.searchParams.get("run")); }); $("close-detail").addEventListener("click", closePanel); $("backdrop").addEventListener("click", closePanel); $("refresh-project").addEventListener("click", refresh); $("timeline-operation").addEventListener("change", () => { state.timelineFilters.operation = $("timeline-operation").value; loadTimeline(); }); $("timeline-outcome").addEventListener("change", () => { state.timelineFilters.outcome = $("timeline-outcome").value; loadTimeline(); }); $("global-search").addEventListener("keydown", (event) => { if (event.key === "Enter" && event.currentTarget.value.trim()) location.href = `?view=timeline&search=${encodeURIComponent(event.currentTarget.value.trim())}`; }); loadCurrent(); const poll = async () => { if (document.hidden) return; try { const body = await api("/api/health"); const generation = body.index && body.index.generation || body.generation || null; if (generation && state.generation && generation !== state.generation) await loadCurrent(); state.generation = generation || state.generation; } catch (_) {} }; state.poll = window.setInterval(poll, 5000); document.addEventListener("visibilitychange", () => { if (!document.hidden) loadCurrent(); }); if (params.get("run")) openRun(params.get("run")); }
  document.addEventListener("DOMContentLoaded", setup);
}());
